<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class CancelamentoService extends FinanceiroCorporativoBaseService
{
 public static function criarComConexaoOficial():self{return new self(conectar());}
 public function solicitar(string $codigo,string $motivo,?string $dataEfetiva=null):array{return $this->executarSeguro('Falha ao solicitar cancelamento','cancelamentos',$codigo,function()use($codigo,$motivo,$dataEfetiva){$a=$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo);if(in_array($a['status'],['cancelada','encerrada'],true))throw new FinanceiroCorporativoException('Assinatura já encerrada.','STATUS_INVALIDO');$data=$dataEfetiva?FinanceiroCorporativoValidator::dataObrigatoria($dataEfetiva,'data_efetiva'):($a['fim_em']?:date('Y-m-d'));$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("UPDATE saas_financeiro_assinaturas SET status='cancelamento_solicitado',cancelamento_solicitado_em=NOW(),cancelamento_efetivo_em=?,motivo_cancelamento=?,renovacao_automatica=0,atualizado_por=? WHERE id=?");$s->bind_param('ssii',$data,$motivo,$uid,$a['id']);$s->execute();$s->close();$this->log->registrarStatus('assinatura',(int)$a['id'],(int)$a['escritorio_id'],$a['tenant_id'],$a['status'],'cancelamento_solicitado',$motivo,['data_efetiva'=>$data]);return $this->sucesso('Cancelamento solicitado.','CANCELAMENTO_SOLICITADO',$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo));});}
 public function efetivar(string $codigo):array{return $this->executarSeguro('Falha ao efetivar cancelamento','cancelamentos',$codigo,function()use($codigo){$a=$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo);if($a['status']!=='cancelamento_solicitado')throw new FinanceiroCorporativoException('Cancelamento não solicitado.','STATUS_INVALIDO');$pend=$this->buscarUm("SELECT COUNT(*) qtd,COALESCE(SUM(saldo_aberto),0) saldo FROM saas_financeiro_cobrancas WHERE assinatura_id=? AND status NOT IN ('cancelada','estornada','paga')",'i',[$a['id']]);$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("UPDATE saas_financeiro_assinaturas SET status='cancelada',fim_em=COALESCE(cancelamento_efetivo_em,CURDATE()),atualizado_por=? WHERE id=?");$s->bind_param('ii',$uid,$a['id']);$s->execute();$s->close();$this->log->registrarStatus('assinatura',(int)$a['id'],(int)$a['escritorio_id'],$a['tenant_id'],$a['status'],'cancelada','Cancelamento efetivado.',['obrigacoes_pendentes'=>$pend]);return $this->sucesso('Cancelamento efetivado sem excluir histórico.','CANCELAMENTO_EFETIVADO',['assinatura'=>$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo),'obrigacoes_pendentes'=>$pend]);});}
 public function impacto(string $codigo):array{return $this->executarSeguro('Falha ao calcular impacto','cancelamentos',$codigo,function()use($codigo){$a=$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo);$c=$this->buscarUm("SELECT COUNT(*) quantidade,COALESCE(SUM(saldo_aberto),0) saldo FROM saas_financeiro_cobrancas WHERE assinatura_id=? AND saldo_aberto>0 AND status NOT IN ('cancelada','estornada')",'i',[$a['id']]);return $this->sucesso('Impacto calculado.','IMPACTO_CANCELAMENTO',['assinatura'=>$a,'cobrancas_pendentes'=>$c,'acao_licenca'=>'preparar_avaliacao_manual']);});}
}
