<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';

final class CreditoService extends FinanceiroCorporativoBaseService
{
    public static function criarComConexaoOficial(): self { return new self(conectar()); }
    public function criar(array $dados): array
    {
        return $this->executarSeguro('Falha ao criar crédito','creditos',null,function() use($dados){$eid=FinanceiroCorporativoValidator::inteiroPositivo($dados['escritorio_id']??null,'escritorio_id');$e=$this->escritorio($eid);$origem=FinanceiroCorporativoValidator::enum($dados['origem']??'','origem',['pagamento_excedente','ajuste','cortesia','estorno','negociacao','outro']);$valor=FinanceiroCorporativoValidator::dinheiro($dados['valor']??'0','valor',false);$codigo=FinanceiroCorporativoCodigo::gerar('CRE');$pag=FinanceiroCorporativoValidator::inteiroOpcional($dados['pagamento_id']??null,'pagamento_id');$valido=FinanceiroCorporativoValidator::dataOpcional($dados['valido_ate']??null,'valido_ate');$motivo=FinanceiroCorporativoValidator::textoOpcional($dados['motivo']??null,500);$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("INSERT INTO saas_financeiro_creditos (codigo,escritorio_id,tenant_id,pagamento_id,origem,status,valor_original,valor_utilizado,saldo_disponivel,valido_ate,motivo,criado_por) VALUES (?,?,?, ?,?,'disponivel',?,'0.00',?,?,?,?)");$s->bind_param('sisissssssi',$codigo,$e['id'],$e['tenant_id'],$pag,$origem,$valor,$valor,$valido,$motivo,$uid);$s->execute();$id=(int)$this->conn->insert_id;$s->close();$this->log->registrarStatus('credito',$id,(int)$e['id'],$e['tenant_id'],null,'disponivel','Crédito criado.');return $this->sucesso('Crédito criado.','CREDITO_CRIADO',$this->entidadePorCodigo('saas_financeiro_creditos',$codigo));});
    }
    public function utilizar(string $codigo,int $cobrancaId,string $valor): array
    {
        return $this->executarSeguro('Falha ao utilizar crédito','creditos',$codigo,function() use($codigo,$cobrancaId,$valor){$cr=$this->entidadePorCodigo('saas_financeiro_creditos',$codigo);$v=FinanceiroCorporativoValidator::dinheiro($valor,'valor',false);if($cr['status']!=='disponivel')throw new FinanceiroCorporativoException('Crédito indisponível.','STATUS_INVALIDO');if(FinanceiroCorporativoValidator::compararDinheiro($v,$cr['saldo_disponivel'])>0)throw new FinanceiroCorporativoException('Saldo de crédito insuficiente.','SALDO_INSUFICIENTE');$uid=$this->usuarioIdAtual();$r=FinanceiroCorporativoTransaction::executar($this->conn,function() use($cr,$cobrancaId,$v,$uid){$c=$this->buscarUm('SELECT * FROM saas_financeiro_cobrancas WHERE id=? FOR UPDATE','i',[$cobrancaId]);if(!$c||(int)$c['escritorio_id']!==(int)$cr['escritorio_id'])throw new FinanceiroCorporativoException('Cobrança inválida.','COBRANCA_INVALIDA');if(FinanceiroCorporativoValidator::compararDinheiro($v,$c['saldo_aberto'])>0)throw new FinanceiroCorporativoException('Crédito superior ao saldo da cobrança.','VALIDACAO_FALHOU');$s=$this->conn->prepare("INSERT INTO saas_financeiro_credito_utilizacoes (credito_id,cobranca_id,valor_utilizado,status,criado_por) VALUES (?,?,?,'ativa',?)");$s->bind_param('iisi',$cr['id'],$cobrancaId,$v,$uid);$s->execute();$s->close();$util=FinanceiroCorporativoValidator::somarDinheiro($cr['valor_utilizado'],$v);$saldo=FinanceiroCorporativoValidator::subtrairDinheiro($cr['saldo_disponivel'],$v);$st=FinanceiroCorporativoValidator::compararDinheiro($saldo,'0.00')===0?'utilizado':'disponivel';$u=$this->conn->prepare('UPDATE saas_financeiro_creditos SET valor_utilizado=?,saldo_disponivel=?,status=? WHERE id=?');$u->bind_param('sssi',$util,$saldo,$st,$cr['id']);$u->execute();$u->close();$vp=FinanceiroCorporativoValidator::somarDinheiro($c['valor_pago'],$v);$sa=FinanceiroCorporativoValidator::subtrairDinheiro($c['saldo_aberto'],$v);$cs=FinanceiroCorporativoValidator::compararDinheiro($sa,'0.00')===0?'paga':'parcial';$u=$this->conn->prepare('UPDATE saas_financeiro_cobrancas SET valor_pago=?,saldo_aberto=?,status=? WHERE id=?');$u->bind_param('sssi',$vp,$sa,$cs,$cobrancaId);$u->execute();$u->close();return ['saldo_credito'=>$saldo,'saldo_cobranca'=>$sa];});return $this->sucesso('Crédito utilizado.','CREDITO_UTILIZADO',$r);});
    }
    public function cancelarUtilizacao(int $utilizacaoId,string $motivo): array { return $this->executarSeguro('Falha ao cancelar utilização','creditos',null,function() use($utilizacaoId,$motivo){$u=$this->buscarUm('SELECT * FROM saas_financeiro_credito_utilizacoes WHERE id=? AND status=\'ativa\'','i',[$utilizacaoId]);if(!$u)throw new FinanceiroCorporativoException('Utilização não encontrada.','REGISTRO_NAO_ENCONTRADO');$uid=$this->usuarioIdAtual();FinanceiroCorporativoTransaction::executar($this->conn,function() use($u,$motivo,$uid){$s=$this->conn->prepare("UPDATE saas_financeiro_credito_utilizacoes SET status='cancelada',cancelado_em=NOW(),motivo_cancelamento=?,cancelado_por=? WHERE id=?");$s->bind_param('sii',$motivo,$uid,$u['id']);$s->execute();$s->close();$c=$this->buscarUm('SELECT * FROM saas_financeiro_creditos WHERE id=? FOR UPDATE','i',[$u['credito_id']]);$util=FinanceiroCorporativoValidator::subtrairDinheiro($c['valor_utilizado'],$u['valor_utilizado']);$saldo=FinanceiroCorporativoValidator::somarDinheiro($c['saldo_disponivel'],$u['valor_utilizado']);$s=$this->conn->prepare("UPDATE saas_financeiro_creditos SET valor_utilizado=?,saldo_disponivel=?,status='disponivel' WHERE id=?");$s->bind_param('ssi',$util,$saldo,$c['id']);$s->execute();$s->close();});return $this->sucesso('Utilização cancelada.','CREDITO_UTILIZACAO_CANCELADA');}); }
    public function expirarVencidos(): array { return $this->executarSeguro('Falha ao expirar créditos','creditos',null,function(){$this->conn->query("UPDATE saas_financeiro_creditos SET status='expirado' WHERE status='disponivel' AND valido_ate IS NOT NULL AND valido_ate<CURDATE()");return $this->sucesso('Créditos vencidos processados.','CREDITOS_EXPIRADOS',['afetados'=>$this->conn->affected_rows]);}); }
    public function consultarSaldo(string $codigo): array { return $this->executarSeguro('Falha ao consultar crédito','creditos',$codigo,function()use($codigo){$c=$this->entidadePorCodigo('saas_financeiro_creditos',$codigo);return $this->sucesso('Saldo consultado.','CREDITO_SALDO',['codigo'=>$codigo,'saldo_disponivel'=>$c['saldo_disponivel'],'status'=>$c['status']]);}); }
}
