<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class DescontoService extends FinanceiroCorporativoBaseService
{
    public static function criarComConexaoOficial(): self{return new self(conectar());}
    public function criar(array $d): array{return $this->executarSeguro('Falha ao criar desconto','descontos',null,function()use($d){$codigo=FinanceiroCorporativoCodigo::gerar('DES');$nome=FinanceiroCorporativoValidator::textoObrigatorio($d['nome']??'','nome',150);$tipo=FinanceiroCorporativoValidator::enum($d['tipo']??'','tipo',['percentual','fixo','isencao']);$ap=FinanceiroCorporativoValidator::enum($d['aplicacao']??'','aplicacao',['global','escritorio','assinatura','cobranca','plano','modulo']);$valor=FinanceiroCorporativoValidator::dinheiro($d['valor']??'0','valor');$perc=(string)($d['percentual']??'0.0000');if(!preg_match('/^\d+(?:\.\d{1,4})?$/',$perc))throw new FinanceiroCorporativoException('Percentual inválido.','VALIDACAO_FALHOU');if($tipo==='percentual' && (float)$perc>100)throw new FinanceiroCorporativoException('Percentual superior a 100%.','VALIDACAO_FALHOU');$eid=FinanceiroCorporativoValidator::inteiroOpcional($d['escritorio_id']??null,'escritorio_id');$aid=FinanceiroCorporativoValidator::inteiroOpcional($d['assinatura_id']??null,'assinatura_id');$cid=FinanceiroCorporativoValidator::inteiroOpcional($d['cobranca_id']??null,'cobranca_id');$pid=FinanceiroCorporativoValidator::inteiroOpcional($d['plano_id']??null,'plano_id');$mid=FinanceiroCorporativoValidator::inteiroOpcional($d['modulo_id']??null,'modulo_id');$ini=FinanceiroCorporativoValidator::dataOpcional($d['inicio_em']??null,'inicio_em');$fim=FinanceiroCorporativoValidator::dataOpcional($d['fim_em']??null,'fim_em');$lim=isset($d['limite_valor'])?FinanceiroCorporativoValidator::dinheiro($d['limite_valor'],'limite_valor'):null;$qmax=FinanceiroCorporativoValidator::inteiroOpcional($d['quantidade_maxima_usos']??null,'quantidade_maxima_usos');$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("INSERT INTO saas_financeiro_descontos (codigo,nome,tipo,aplicacao,escritorio_id,assinatura_id,cobranca_id,plano_id,modulo_id,valor,percentual,limite_valor,inicio_em,fim_em,quantidade_maxima_usos,status,criado_por) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'ativo',?)");$s->bind_param('ssssiiiiisssssii',$codigo,$nome,$tipo,$ap,$eid,$aid,$cid,$pid,$mid,$valor,$perc,$lim,$ini,$fim,$qmax,$uid);$s->execute();$s->close();return $this->sucesso('Desconto criado.','DESCONTO_CRIADO',$this->entidadePorCodigo('saas_financeiro_descontos',$codigo));});}
    public function calcular(string $codigo,string $valorElegivel): array{return $this->executarSeguro('Falha ao calcular desconto','descontos',$codigo,function()use($codigo,$valorElegivel){$d=$this->entidadePorCodigo('saas_financeiro_descontos',$codigo);$base=FinanceiroCorporativoValidator::dinheiro($valorElegivel,'valor_elegivel');if($d['status']!=='ativo')throw new FinanceiroCorporativoException('Desconto inativo.','STATUS_INVALIDO');$hoje=date('Y-m-d');if(($d['inicio_em']&&$d['inicio_em']>$hoje)||($d['fim_em']&&$d['fim_em']<$hoje))throw new FinanceiroCorporativoException('Desconto fora da vigência.','DESCONTO_FORA_VIGENCIA');if($d['quantidade_maxima_usos']!==null && (int)$d['quantidade_usos']>=(int)$d['quantidade_maxima_usos'])throw new FinanceiroCorporativoException('Limite de usos atingido.','DESCONTO_ESGOTADO');if($d['tipo']==='isencao')$desc=$base;elseif($d['tipo']==='fixo')$desc=$d['valor'];else{$bp=(int)round((float)$d['percentual']*100);$cent=(int)round((float)$base*100);$desc=number_format(intdiv($cent*$bp,10000)/100,2,'.','');}if($d['limite_valor']!==null && FinanceiroCorporativoValidator::compararDinheiro($desc,$d['limite_valor'])>0)$desc=$d['limite_valor'];if(FinanceiroCorporativoValidator::compararDinheiro($desc,$base)>0)$desc=$base;return $this->sucesso('Desconto calculado.','DESCONTO_CALCULADO',['valor_desconto'=>$desc,'valor_final'=>FinanceiroCorporativoValidator::subtrairDinheiro($base,$desc)]);});}
    public function ativar(string $codigo):array{return $this->status($codigo,'ativo');} public function inativar(string $codigo):array{return $this->status($codigo,'inativo');}
    private function status(string $codigo,string $st):array{return $this->executarSeguro('Falha ao atualizar desconto','descontos',$codigo,function()use($codigo,$st){$d=$this->entidadePorCodigo('saas_financeiro_descontos',$codigo);$s=$this->conn->prepare('UPDATE saas_financeiro_descontos SET status=? WHERE id=?');$s->bind_param('si',$st,$d['id']);$s->execute();$s->close();return $this->sucesso('Desconto atualizado.','DESCONTO_ATUALIZADO',$this->entidadePorCodigo('saas_financeiro_descontos',$codigo));});}
}
