<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class FluxoCaixaCorporativoService extends FinanceiroCorporativoBaseService
{
 public static function criarComConexaoOficial():self{return new self(conectar());}
 public function criarLancamento(array $d):array{return $this->executarSeguro('Falha ao criar lançamento','lancamentos',null,function()use($d){$tipo=FinanceiroCorporativoValidator::enum($d['tipo']??'','tipo',['receita','despesa','ajuste','transferencia']);$natureza=FinanceiroCorporativoValidator::enum($d['natureza']??'','natureza',['entrada','saida']);$desc=FinanceiroCorporativoValidator::textoObrigatorio($d['descricao']??'','descricao',255);$valor=FinanceiroCorporativoValidator::dinheiro($d['valor_previsto']??'0','valor_previsto');$codigo=FinanceiroCorporativoCodigo::gerar('LAN');$conta=FinanceiroCorporativoValidator::inteiroOpcional($d['conta_id']??null,'conta_id');$cat=FinanceiroCorporativoValidator::inteiroOpcional($d['categoria_id']??null,'categoria_id');$cc=FinanceiroCorporativoValidator::inteiroOpcional($d['centro_custo_id']??null,'centro_custo_id');$eid=FinanceiroCorporativoValidator::inteiroOpcional($d['escritorio_id']??null,'escritorio_id');$tenant=null;if($eid){$tenant=$this->escritorio($eid)['tenant_id'];}$venc=FinanceiroCorporativoValidator::dataOpcional($d['vencimento_em']??null,'vencimento_em');$comp=FinanceiroCorporativoValidator::textoOpcional($d['competencia']??null,7);$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("INSERT INTO saas_financeiro_lancamentos (codigo,tipo,natureza,status,descricao,competencia,conta_id,categoria_id,centro_custo_id,escritorio_id,tenant_id,valor_previsto,valor_realizado,vencimento_em,criado_por) VALUES (?,?,?,'previsto',?,?,?,?,?,?,?,?, '0.00',?,?)");$s->bind_param('ssssiiiiisssi',$codigo,$tipo,$natureza,$desc,$comp,$conta,$cat,$cc,$eid,$tenant,$valor,$venc,$uid);$s->execute();$id=(int)$this->conn->insert_id;$s->close();$this->log->registrarStatus('lancamento',$id,$eid,$tenant,null,'previsto','Lançamento criado.');return $this->sucesso('Lançamento criado.','LANCAMENTO_CRIADO',$this->entidadePorCodigo('saas_financeiro_lancamentos',$codigo));});}
 public function realizar(string $codigo,string $valor,?string $data=null):array{return $this->executarSeguro('Falha ao realizar lançamento','lancamentos',$codigo,function()use($codigo,$valor,$data){$l=$this->entidadePorCodigo('saas_financeiro_lancamentos',$codigo);if($l['status']!=='previsto')throw new FinanceiroCorporativoException('Lançamento não está previsto.','STATUS_INVALIDO');$v=FinanceiroCorporativoValidator::dinheiro($valor,'valor',false);$dt=$data?:date('Y-m-d H:i:s');$uid=$this->usuarioIdAtual();$s=$this->conn->prepare("UPDATE saas_financeiro_lancamentos SET status='realizado',valor_realizado=?,realizado_em=?,atualizado_por=? WHERE id=?");$s->bind_param('ssii',$v,$dt,$uid,$l['id']);$s->execute();$s->close();$this->log->registrarStatus('lancamento',(int)$l['id'],$l['escritorio_id']?:(null),$l['tenant_id'],$l['status'],'realizado','Lançamento realizado.');return $this->sucesso('Lançamento realizado.','LANCAMENTO_REALIZADO',$this->entidadePorCodigo('saas_financeiro_lancamentos',$codigo));});}
 public function cancelar(string $codigo,string $motivo):array{return $this->executarSeguro('Falha ao cancelar lançamento','lancamentos',$codigo,function()use($codigo,$motivo){$l=$this->entidadePorCodigo('saas_financeiro_lancamentos',$codigo);$s=$this->conn->prepare("UPDATE saas_financeiro_lancamentos SET status='cancelado',cancelado_em=NOW(),motivo_cancelamento=? WHERE id=?");$s->bind_param('si',$motivo,$l['id']);$s->execute();$s->close();return $this->sucesso('Lançamento cancelado.','LANCAMENTO_CANCELADO',$this->entidadePorCodigo('saas_financeiro_lancamentos',$codigo));});}
 public function transferir(int $origem,int $destino,string $valor,array $d=[]):array{return $this->executarSeguro('Falha ao transferir','transferencias',null,function()use($origem,$destino,$valor,$d){if($origem===$destino)throw new FinanceiroCorporativoException('Contas devem ser diferentes.','VALIDACAO_FALHOU');$v=FinanceiroCorporativoValidator::dinheiro($valor,'valor',false);$taxa=FinanceiroCorporativoValidator::dinheiro($d['taxa']??'0','taxa');$codigo=FinanceiroCorporativoCodigo::gerar('TRF');$uid=$this->usuarioIdAtual();$res=FinanceiroCorporativoTransaction::executar($this->conn,function()use($origem,$destino,$v,$taxa,$codigo,$uid){foreach([$origem,$destino] as $id)if(!$this->buscarUm("SELECT id FROM saas_financeiro_contas WHERE id=? AND status='ativa'",'i',[$id]))throw new FinanceiroCorporativoException('Conta inválida.','CONTA_INVALIDA');$s=$this->conn->prepare("INSERT INTO saas_financeiro_transferencias (codigo,conta_origem_id,conta_destino_id,status,valor,taxa,transferida_em,criado_por) VALUES (?,?,?,'realizada',?,?,NOW(),?)");$s->bind_param('siissi',$codigo,$origem,$destino,$v,$taxa,$uid);$s->execute();$id=(int)$this->conn->insert_id;$s->close();return ['id'=>$id,'codigo'=>$codigo];});return $this->sucesso('Transferência registrada sem contar como receita/despesa.','TRANSFERENCIA_REALIZADA',$res);});}
 public function saldoConta(int $contaId):array{return $this->executarSeguro('Falha ao consultar saldo','contas',null,function()use($contaId){$c=$this->buscarUm('SELECT * FROM saas_financeiro_contas WHERE id=?','i',[$contaId]);if(!$c)throw new FinanceiroCorporativoException('Conta não encontrada.','CONTA_NAO_ENCONTRADA');$m=$this->buscarUm("SELECT COALESCE(SUM(CASE WHEN natureza='entrada' THEN valor_realizado ELSE -valor_realizado END),0) movimento FROM saas_financeiro_lancamentos WHERE conta_id=? AND status='realizado' AND tipo<>'transferencia'",'i',[$contaId]);$saldo=FinanceiroCorporativoValidator::somarDinheiro($c['saldo_inicial'],(string)$m['movimento']);return $this->sucesso('Saldo calculado.','SALDO_CONTA',['conta'=>$c,'saldo'=>$saldo]);});}
 public function fluxo(string $inicio,string $fim):array{return $this->executarSeguro('Falha ao consultar fluxo','lancamentos',null,function()use($inicio,$fim){$i=FinanceiroCorporativoValidator::dataObrigatoria($inicio,'inicio');$f=FinanceiroCorporativoValidator::dataObrigatoria($fim,'fim');$r=$this->listarSql("SELECT DATE(COALESCE(realizado_em,vencimento_em)) data,natureza,status,SUM(valor_previsto) previsto,SUM(valor_realizado) realizado FROM saas_financeiro_lancamentos WHERE COALESCE(DATE(realizado_em),vencimento_em) BETWEEN ? AND ? AND tipo<>'transferencia' GROUP BY data,natureza,status ORDER BY data",'ss',[$i,$f]);return $this->sucesso('Fluxo calculado.','FLUXO_CAIXA',['itens'=>$r]);});}
}
