<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class IndicadoresSaasService extends FinanceiroCorporativoBaseService
{
 public static function criarComConexaoOficial():self{return new self(conectar());}
 public function resumo(?string $inicio=null,?string $fim=null):array{return $this->executarSeguro('Falha ao calcular indicadores','indicadores',null,function()use($inicio,$fim){$inicio=$inicio?FinanceiroCorporativoValidator::dataObrigatoria($inicio,'inicio'):date('Y-m-01');$fim=$fim?FinanceiroCorporativoValidator::dataObrigatoria($fim,'fim'):date('Y-m-t');$mrr=$this->buscarUm("SELECT COALESCE(SUM(CASE periodicidade WHEN 'mensal' THEN valor_final WHEN 'trimestral' THEN valor_final/3 WHEN 'semestral' THEN valor_final/6 WHEN 'anual' THEN valor_final/12 ELSE 0 END),0) valor FROM saas_financeiro_assinaturas WHERE status='ativa'");$recebida=$this->buscarUm("SELECT COALESCE(SUM(valor_liquido),0) valor FROM saas_financeiro_pagamentos WHERE status IN ('confirmado','compensado') AND DATE(COALESCE(compensado_em,recebido_em)) BETWEEN ? AND ?",'ss',[$inicio,$fim]);$prevista=$this->buscarUm("SELECT COALESCE(SUM(saldo_aberto),0) valor FROM saas_financeiro_cobrancas WHERE status IN ('emitida','aberta','parcial','vencida') AND vencimento_em BETWEEN ? AND ?",'ss',[$inicio,$fim]);$inad=$this->buscarUm("SELECT COUNT(*) quantidade,COALESCE(SUM(saldo_aberto),0) valor FROM saas_financeiro_cobrancas WHERE status='vencida' AND saldo_aberto>0");$ass=$this->buscarUm("SELECT COUNT(*) total,SUM(status='ativa') ativas,SUM(status='trial') trials,SUM(status='cancelada') canceladas FROM saas_financeiro_assinaturas");$creditos=$this->buscarUm("SELECT COALESCE(SUM(saldo_disponivel),0) valor FROM saas_financeiro_creditos WHERE status='disponivel'");$mrrv=(string)($mrr['valor']??'0.00');$arr=number_format((float)$mrrv*12,2,'.','');$ticket=(int)($ass['ativas']??0)>0?number_format((float)$mrrv/(int)$ass['ativas'],2,'.',''):'0.00';$this->log->registrarEvento('Consultou indicadores SaaS','indicadores',null,'Indicadores calculados sem dashboard.');return $this->sucesso('Indicadores calculados.','INDICADORES_CALCULADOS',['periodo'=>['inicio'=>$inicio,'fim'=>$fim],'mrr'=>$mrrv,'arr'=>$arr,'receita_recebida'=>(string)$recebida['valor'],'receita_prevista'=>(string)$prevista['valor'],'inadimplencia'=>$inad,'assinaturas'=>$ass,'creditos_disponiveis'=>(string)$creditos['valor'],'ticket_medio'=>$ticket]);});}
 public function receitaPorPlano():array{return $this->executarSeguro('Falha ao calcular receita por plano','indicadores',null,function(){$r=$this->listarSql("SELECT COALESCE(plano_nome_snapshot,'Sem plano') plano,COUNT(*) assinaturas,SUM(valor_final) valor_contratado FROM saas_financeiro_assinaturas WHERE status='ativa' GROUP BY plano_nome_snapshot ORDER BY valor_contratado DESC");return $this->sucesso('Receita por plano calculada.','RECEITA_POR_PLANO',['itens'=>$r]);});}
 public function receitaPorEscritorio(string $inicio,string $fim):array{return $this->executarSeguro('Falha ao calcular receita por escritório','indicadores',null,function()use($inicio,$fim){$i=FinanceiroCorporativoValidator::dataObrigatoria($inicio,'inicio');$f=FinanceiroCorporativoValidator::dataObrigatoria($fim,'fim');$r=$this->listarSql("SELECT p.escritorio_id,e.nome escritorio,SUM(p.valor_liquido) receita FROM saas_financeiro_pagamentos p LEFT JOIN escritorios_saas e ON e.id=p.escritorio_id WHERE p.status IN ('confirmado','compensado') AND DATE(COALESCE(p.compensado_em,p.recebido_em)) BETWEEN ? AND ? GROUP BY p.escritorio_id,e.nome ORDER BY receita DESC",'ss',[$i,$f]);return $this->sucesso('Receita por escritório calculada.','RECEITA_POR_ESCRITORIO',['itens'=>$r]);});}
 public function churn(string $inicio,string $fim):array{return $this->executarSeguro('Falha ao calcular churn','indicadores',null,function()use($inicio,$fim){$i=FinanceiroCorporativoValidator::dataObrigatoria($inicio,'inicio');$f=FinanceiroCorporativoValidator::dataObrigatoria($fim,'fim');$ini=$this->buscarUm("SELECT COUNT(*) total FROM saas_financeiro_assinaturas WHERE inicio_em<? AND (fim_em IS NULL OR fim_em>=?)",'ss',[$i,$i]);$cancel=$this->buscarUm("SELECT COUNT(*) total FROM saas_financeiro_assinaturas WHERE status IN ('cancelada','encerrada') AND fim_em BETWEEN ? AND ?",'ss',[$i,$f]);$base=max(1,(int)$ini['total']);$taxa=number_format(((int)$cancel['total']/$base)*100,2,'.','');return $this->sucesso('Churn calculado.','CHURN_CALCULADO',['base_inicial'=>(int)$ini['total'],'cancelamentos'=>(int)$cancel['total'],'percentual'=>$taxa]);});}
 public function conversaoTrial(string $inicio,string $fim):array{return $this->executarSeguro('Falha ao calcular conversão trial','indicadores',null,function()use($inicio,$fim){$i=FinanceiroCorporativoValidator::dataObrigatoria($inicio,'inicio');$f=FinanceiroCorporativoValidator::dataObrigatoria($fim,'fim');$r=$this->buscarUm("SELECT COUNT(*) trials,SUM(trial_convertido_em IS NOT NULL) convertidos FROM saas_financeiro_assinaturas WHERE trial_inicio_em BETWEEN ? AND ?",'ss',[$i,$f]);$tr=max(1,(int)$r['trials']);$r['percentual']=number_format(((int)$r['convertidos']/$tr)*100,2,'.','');return $this->sucesso('Conversão calculada.','CONVERSAO_TRIAL',$r);});}
}
