<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class LicencaFinanceiraService extends FinanceiroCorporativoBaseService
{
 public static function criarComConexaoOficial():self{return new self(conectar());}
 public function consultar(int $licencaId,int $escritorioId):array{return $this->executarSeguro('Falha ao consultar licença financeira','licencas',null,function()use($licencaId,$escritorioId){$l=$this->buscarUm('SELECT * FROM licencas_saas WHERE id=? AND escritorio_id=? LIMIT 1','ii',[$licencaId,$escritorioId]);if(!$l)throw new FinanceiroCorporativoException('Licença não encontrada para o escritório.','LICENCA_NAO_ENCONTRADA');return $this->sucesso('Licença localizada.','LICENCA_LOCALIZADA',$l);});}
 public function prepararSuspensao(int $licencaId,int $escritorioId):array{return $this->executarSeguro('Falha ao preparar suspensão','licencas',null,function()use($licencaId,$escritorioId){$l=$this->buscarUm('SELECT * FROM licencas_saas WHERE id=? AND escritorio_id=? LIMIT 1','ii',[$licencaId,$escritorioId]);if(!$l)throw new FinanceiroCorporativoException('Licença inválida.','LICENCA_NAO_ENCONTRADA');$d=$this->buscarUm("SELECT MAX(DATEDIFF(CURDATE(),vencimento_em)) dias,COALESCE(SUM(saldo_aberto),0) saldo FROM saas_financeiro_cobrancas WHERE escritorio_id=? AND status='vencida'",'i',[$escritorioId]);return $this->sucesso('Avaliação preparada; nenhuma alteração executada.','SUSPENSAO_PREPARADA',['licenca'=>$l,'inadimplencia'=>$d,'requer_autorizacao_explicita'=>true]);});}
 public function suspenderAutorizado(int $licencaId,int $escritorioId,string $motivo,bool $autorizado):array{return $this->alterar($licencaId,$escritorioId,'suspensa',$motivo,$autorizado,'LICENCA_SUSPENSA');}
 public function reativarAutorizado(int $licencaId,int $escritorioId,string $motivo,bool $autorizado):array{return $this->alterar($licencaId,$escritorioId,'ativa',$motivo,$autorizado,'LICENCA_REATIVADA');}
 private function alterar(int $licencaId,int $escritorioId,string $novo,string $motivo,bool $autorizado,string $ret):array{return $this->executarSeguro('Falha ao alterar licença','licencas',null,function()use($licencaId,$escritorioId,$novo,$motivo,$autorizado,$ret){if(!$autorizado)throw new FinanceiroCorporativoException('Autorização explícita obrigatória.','AUTORIZACAO_OBRIGATORIA');$l=$this->buscarUm('SELECT * FROM licencas_saas WHERE id=? AND escritorio_id=? LIMIT 1','ii',[$licencaId,$escritorioId]);if(!$l)throw new FinanceiroCorporativoException('Licença inválida.','LICENCA_NAO_ENCONTRADA');$col=$this->buscarUm("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='licencas_saas' AND COLUMN_NAME IN ('status','situacao') ORDER BY FIELD(COLUMN_NAME,'status','situacao') LIMIT 1");if(!$col)throw new FinanceiroCorporativoException('Campo de status da licença não identificado.','ESTRUTURA_INCOMPATIVEL');$campo=$col['COLUMN_NAME'];$s=$this->conn->prepare("UPDATE licencas_saas SET `$campo`=? WHERE id=? AND escritorio_id=?");$s->bind_param('sii',$novo,$licencaId,$escritorioId);$s->execute();$s->close();$this->log->registrarEvento('Alterou licença por decisão financeira autorizada','licencas',(string)$licencaId,$motivo,['dados_anteriores'=>[$campo=>$l[$campo]??null],'dados_novos'=>[$campo=>$novo],'escritorio_id'=>$escritorioId]);return $this->sucesso('Licença atualizada com autorização explícita.',$ret,['licenca_id'=>$licencaId,'status'=>$novo]);});}
}
