<?php
declare(strict_types=1);
require_once __DIR__ . '/FinanceiroCorporativoBaseService.php';
final class RenovacaoService extends FinanceiroCorporativoBaseService
{
 public static function criarComConexaoOficial():self{return new self(conectar());}
 public function proximas(int $dias=30):array{return $this->executarSeguro('Falha ao listar renovações','renovacoes',null,function()use($dias){$dias=max(1,min(365,$dias));$rows=$this->listarSql("SELECT * FROM saas_financeiro_assinaturas WHERE status IN ('ativa','trial') AND renovacao_automatica=1 AND renovacao_em BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL ? DAY) ORDER BY renovacao_em",'i',[$dias]);return $this->sucesso('Renovações listadas.','RENOVACOES_LISTADAS',['itens'=>$rows]);});}
 public function renovar(string $codigo,?string $novoValor=null):array{return $this->executarSeguro('Falha ao renovar assinatura','renovacoes',$codigo,function()use($codigo,$novoValor){$a=$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo);if(!in_array($a['status'],['ativa','trial'],true))throw new FinanceiroCorporativoException('Assinatura não renovável.','STATUS_INVALIDO');$data=new DateTimeImmutable($a['renovacao_em']?:date('Y-m-d'));$add=match($a['periodicidade']){'anual'=>'+1 year','semestral'=>'+6 months','trimestral'=>'+3 months',default=>'+1 month'};$nova=$data->modify($add)->format('Y-m-d');$valor=$novoValor===null?$a['valor_final']:FinanceiroCorporativoValidator::dinheiro($novoValor,'novo_valor');$uid=$this->usuarioIdAtual();$s=$this->conn->prepare('UPDATE saas_financeiro_assinaturas SET renovacao_em=?,proxima_cobranca_em=?,valor_final=?,atualizado_por=? WHERE id=?');$s->bind_param('sssii',$nova,$nova,$valor,$uid,$a['id']);$s->execute();$s->close();$this->log->registrarStatus('assinatura',(int)$a['id'],(int)$a['escritorio_id'],$a['tenant_id'],$a['status'],$a['status'],'Assinatura renovada.',['renovacao_anterior'=>$a['renovacao_em'],'renovacao_nova'=>$nova]);return $this->sucesso('Assinatura renovada.','ASSINATURA_RENOVADA',$this->entidadePorCodigo('saas_financeiro_assinaturas',$codigo));});}
}
