CREATE TABLE IF NOT EXISTS documentos_arquivos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    titulo VARCHAR(180) NOT NULL,
    categoria VARCHAR(80) NOT NULL DEFAULT 'Documento geral',
    cliente_id VARCHAR(10) NULL,
    processo_id VARCHAR(10) NULL,
    numero_processo VARCHAR(80) NULL,
    descricao TEXT NULL,
    nome_original VARCHAR(255) NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho VARCHAR(255) NOT NULL,
    extensao VARCHAR(20) NULL,
    mime_type VARCHAR(120) NULL,
    tamanho_bytes BIGINT DEFAULT 0,
    hash_arquivo VARCHAR(64) NULL,
    usuario_id INT NULL,
    usuario_nome VARCHAR(150) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Ativo',
    deletado TINYINT(1) NOT NULL DEFAULT 0,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_doc_codigo (codigo),
    INDEX idx_doc_cliente (cliente_id),
    INDEX idx_doc_processo (processo_id),
    INDEX idx_doc_categoria (categoria),
    INDEX idx_doc_deletado (deletado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
